clients-data-file: /tmp/connections.yaml

tmp: /tmp

examples-dir: /vagrant/examples

extensions-dir: /vagrant/solar/solar/extensions

file-system-db:
  storage-path: /tmp/storage

template-dir: /vagrant/templates

resources-files-mask: /vagrant/resources/*/*.yaml
node_resource_template: /vagrant/resources/ro_node/

state: /tmp/state/

