id: docker
handler: ansible
version: 1.0.0

input:
    ip:
      schema: str!
      value:
    ssh_user:
      schema: str!
      value:
    ssh_key:
      schema: str!
      value:

tags: [resources/docker]
