
- hosts: [{{host}}]]
  sudo: yes
  tasks:
    - shell: docker --version
      ignore_errors: true
      register: docker_version
    - shell: curl -sSL https://get.docker.com/ | sudo sh
      when: docker_version|failed
